In [1]:
import pandas as pd
import numpy as np

In [2]:
df =pd.read_csv('Flipkart_Mobiles.csv')

In [3]:
df.head()

Brand Model            Color Memory Storage  Rating  Selling Price  \
0  OPPO   A53  Moonlight Black   4 GB   64 GB     4.5          11990   
1  OPPO   A53       Mint Cream   4 GB   64 GB     4.5          11990   
2  OPPO   A53  Moonlight Black   6 GB  128 GB     4.3          13990   
3  OPPO   A53       Mint Cream   6 GB  128 GB     4.3          13990   
4  OPPO   A53   Electric Black   4 GB   64 GB     4.5          11990   

   Original Price  
0           15990  
1           15990  
2           17990  
3           17990  
4           15990

In [4]:
df.shape

(3114, 8)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3114 entries, 0 to 3113
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   Brand           3114 non-null   object 
 1   Model           3114 non-null   object 
 2   Color           3114 non-null   object 
 3   Memory          3071 non-null   object 
 4   Storage         3075 non-null   object 
 5   Rating          2970 non-null   float64
 6   Selling Price   3114 non-null   int64  
 7   Original Price  3114 non-null   int64  
dtypes: float64(1), int64(2), object(5)
memory usage: 194.8+ KB


In [6]:
df['Rating'].unique()

array([4.5, 4.3, 4.4, 4.2, nan, 4. , 4.6, 3.8, 3. , 4.1, 3.7, 3.1, 4.7,
       3.9, 3.4, 3.3, 3.6, 3.5, 3.2, 2.7, 2.8, 5. , 2.4, 2.3, 4.9, 4.8])

In [7]:
df['Selling Price'].unique()

array([ 11990,  13990,  10490,   9490,  15990,  17990,  11960,  11779,
        18979,   8990,  19990,  14990,  29990,  16990,  12199,  21990,
        15999,  13850,  35990,  10990,  13499,  18380,  39990,  26798,
        12990,  27990,  23490,  25990,  12889,   9989,  24989,  11249,
        24990,  29999,  29489,  20999,  24719,  24768,  60990,  34990,
        17000,  27500,  15000,  18000,  11000,  23990,  19000,  15500,
        17999,   9940,  10000,  15726,  12500,  18990,  13799,  13899,
        25889,  13490,   8490,  15677,  12000,  21150,  14995,   9500,
        13750,  13500,  22990,  13489,  18490,   7990,  20990,   9990,
        30994,  17890,  30990,  21999,  21452,  16890,   4999,  15739,
        38990,  38999,  41990,  24900,  56990,  12999,  16999,  13999,
        37990,  31999,  44999,  69999,  71000,  80000,  83000,  92000,
        39999,  76000,  82000,  61000,  70000,  66000,  57000,   7690,
        44990,  15532,   9999,  10999,  14999,  13775,   5899,   7999,
      

In [8]:
df['Memory'].unique()

array(['4 GB', '6 GB', '3 GB', '8 GB', '2 GB', '12 GB', '1 GB', '512 MB',
       '1.5 GB', '768 MB', '16 GB', '18 GB', '8 MB', '64 MB', '4 MB',
       '32 MB', '16 MB', '128 MB', nan, '4GB', '153 MB', '2 MB', '10 MB',
       '46 MB', '32 GB', '100 MB', '30 MB'], dtype=object)

In [9]:
df['Color'].unique()

array(['Moonlight Black', 'Mint Cream', 'Electric Black', 'Deep Blue',
       'Black', 'Blue', 'Flowing Silver', 'Crystal Blue', 'Ink Black',
       'Lake Green', 'Mystery Black', 'Fantastic Purple', 'Matte Black',
       'Moonlight Gold', 'Aurora', 'Stellar Black', 'Magic Blue',
       'Starry Blue', 'Crystal Black', 'Metallic White', 'Fantasy White',
       'Navy Blue', 'Fancy Blue', 'Pearl Blue', 'Astral Blue',
       'CRYSTAL BLACK', 'Dynamic Black', 'Dynamic Orange', 'Mystery Blue',
       'Fairy White', 'Fluid Black', 'Sky White', 'Midnight Black',
       'Rainbow Silver', 'Auroral Blue', 'Crystal Silver', 'Space Silver',
       'Fancy White', 'Midnight Blue', 'Glaring Gold', 'Starry Black',
       'Red', 'JET BLACK', 'Luminous Black', 'Unicorn White',
       'Prism Black', 'Piano Black', 'Classic Silver', 'Lightening Black',
       'Marine Green', 'Bordeaux Red', 'Galactic Blue', 'Marble Green',
       'Diamond Blue', 'Silky White', 'Starry Night', 'Space Purple',
       'Dazzli

In [10]:
df['Model'].unique()

array(['A53', 'A12', 'A53s 5G', 'A33', 'A31', 'A74 5G', 'A11K', 'F17 Pro',
       'A54', 'Reno6 5G', 'F17', 'A16', 'Reno5 Pro 5G', 'A15',
       'A74 5G BLACK', 'Reno6 Pro 5G', 'Reno2 F', 'Reno3 Pro', 'A15s',
       'A15S', 'F19 Pro', 'F19 Pro+ 5G', 'F19', 'A7', 'F5', 'A5s', 'Reno',
       'Reno2 Z', 'F15', 'K1', 'A9 2020', 'Find X',
       'Reno4 Pro Special Edition', 'F11', 'A5', 'Reno4 Pro', 'A5 2020',
       'F3 Deepika Padukone Limited Edition', 'F1 Plus',
       'A83 2018 Edition', 'F3', 'A3s', 'A83', 'K3', 'F9', 'A52',
       'A71 New Edition', 'Neo 7 4G', 'A71', 'A57', 'A1K', 'A37f',
       'F9 Pro', 'F19s', 'A71k', 'A9', 'F3 Plus',
       'Rohit Sharma Limited Edition', 'F17 PRO',
       'Hardik Pandya Limited Editon',
       'Ravichandran Ashwin Limited Edition', 'F11 Pro', 'R1 R829',
       'F5 Youth', 'F7', 'Neo 5', 'F1', 'Reno2', 'R17',
       'F11 Pro Marvel’s Avengers Limited Edition', 'Reno 10x Zoom',
       'F1S', 'N5111', 'U11+ ', 'Wildfire X ', '3', '4a ', '3a XL ',


In [11]:
df['Brand'].unique()

array(['OPPO', 'HTC', 'IQOO', 'Google Pixel', 'LG', 'ASUS', 'realme',
       'GIONEE', 'Nokia', 'Apple', 'SAMSUNG', 'Lenovo', 'Motorola',
       'POCO', 'vivo', 'Xiaomi', 'Infinix'], dtype=object)

In [12]:
df['Storage'].unique()

array(['64 GB', '128 GB', '32 GB', '256 GB', '16 GB', '8 GB', '4 GB',
       '512 GB', nan, '16 MB', '128 MB', '2 MB', '4 MB', '48 MB', '8 MB',
       'Expandable Upto 32 GB', 'Expandable Upto 16 GB', '10 MB',
       '256 MB', '140 MB', '64 MB', '1 TB', '153 MB', '512 MB', '100 MB',
       '129 GB', '130 GB'], dtype=object)

In [13]:
df['Rating'].unique()

array([4.5, 4.3, 4.4, 4.2, nan, 4. , 4.6, 3.8, 3. , 4.1, 3.7, 3.1, 4.7,
       3.9, 3.4, 3.3, 3.6, 3.5, 3.2, 2.7, 2.8, 5. , 2.4, 2.3, 4.9, 4.8])

In [14]:
df = df[df['Rating']!="nan"]

In [15]:
df['Rating'].unique()

array([4.5, 4.3, 4.4, 4.2, nan, 4. , 4.6, 3.8, 3. , 4.1, 3.7, 3.1, 4.7,
       3.9, 3.4, 3.3, 3.6, 3.5, 3.2, 2.7, 2.8, 5. , 2.4, 2.3, 4.9, 4.8])

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3114 entries, 0 to 3113
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   Brand           3114 non-null   object 
 1   Model           3114 non-null   object 
 2   Color           3114 non-null   object 
 3   Memory          3071 non-null   object 
 4   Storage         3075 non-null   object 
 5   Rating          2970 non-null   float64
 6   Selling Price   3114 non-null   int64  
 7   Original Price  3114 non-null   int64  
dtypes: float64(1), int64(2), object(5)
memory usage: 219.0+ KB


In [17]:
df=df[~df['Rating'].isna()]

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2970 entries, 0 to 3113
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   Brand           2970 non-null   object 
 1   Model           2970 non-null   object 
 2   Color           2970 non-null   object 
 3   Memory          2928 non-null   object 
 4   Storage         2939 non-null   object 
 5   Rating          2970 non-null   float64
 6   Selling Price   2970 non-null   int64  
 7   Original Price  2970 non-null   int64  
dtypes: float64(1), int64(2), object(5)
memory usage: 208.8+ KB


In [19]:
df=df.reset_index(drop=True)

In [20]:
df.describe()

Rating  Selling Price  Original Price
count  2970.000000    2970.000000     2970.000000
mean      4.243098   24891.598316    26826.261616
std       0.271991   27103.698397    28877.509081
min       2.300000    1000.000000     1000.000000
25%       4.100000    9989.250000    10000.000000
50%       4.300000   14999.000000    15999.000000
75%       4.400000   27499.000000    29999.000000
max       5.000000  179900.000000   189999.000000

In [21]:
df[df['Selling Price']>100000]

Brand               Model           Color Memory Storage  Rating  \
1106  Apple  iPhone 12 Pro Max           Silver    NaN  512 GB     4.6   
1119  Apple      iPhone 12 Pro     Pacific Blue   6 GB  256 GB     4.6   
1123  Apple  iPhone 11 Pro Max   Midnight Green    4GB   64 GB     4.7   
1125  Apple      iPhone 12 Pro             Gold   6 GB  128 GB     4.6   
1126  Apple      iPhone 12 Pro             Gold   6 GB  512 GB     4.6   
...     ...                 ...             ...    ...     ...     ...   
2910  Apple   iPhone 13 Pro Max          Silver    4GB  256 GB     4.7   
2911  Apple   iPhone 13 Pro Max     Sierra Blue    4GB  512 GB     4.7   
2912  Apple   iPhone 13 Pro Max            Gold    4GB  512 GB     4.7   
2913  Apple   iPhone 13 Pro Max        Graphite    4GB    1 TB     4.7   
2914  Apple   iPhone 13 Pro Max     Sierra Blue    4GB    1 TB     4.7   

      Selling Price  Original Price  
1106         149900          149900  
1119         119900          119900  
1123         117100          117100  
1125         109900          109900  
1126         139900          139900  
...             ...             ...  
2910         139900          139900  
2911         159900          159900  
2912         159900          159900  
2913         179900          179900  
2914         179900          179900  

[90 rows x 8 columns]

In [22]:
df.to_csv('clean_mobile.csv')

In [23]:
x= df.drop(columns='Selling Price')
y=df['Selling Price']

In [24]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y, test_size=0.2)

In [25]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import make_column_transformer
from sklearn.pipeline import make_pipeline

In [26]:
ohe= OneHotEncoder(handle_unknown='ignore')
ohe.fit(x[['Brand','Model','Color','Memory','Storage','Rating','Original Price']])

OneHotEncoder(handle_unknown='ignore')

In [27]:
column_trans =make_column_transformer((OneHotEncoder(categories=ohe.categories_),['Brand','Model','Color','Memory','Storage','Rating','Original Price']),
                                     remainder='passthrough')

In [28]:
lr=LinearRegression()

In [29]:
pipe =make_pipeline(column_trans,lr)

In [30]:
pipe.fit(x_train,y_train)

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('onehotencoder',
                                                  OneHotEncoder(categories=[array(['ASUS', 'Apple', 'GIONEE', 'Google Pixel', 'HTC', 'IQOO',
       'Infinix', 'LG', 'Lenovo', 'Motorola', 'Nokia', 'OPPO', 'POCO',
       'SAMSUNG', 'Xiaomi', 'realme', 'vivo'], dtype=object),
                                                                            array(['1', '10', '105', '105 DS', '105 DS 2020', '105 SS 2...
        95000,  95999,  99900,  99999, 100999, 103000, 103900, 104999,
       106600, 106900, 109900, 116000, 117100, 117990, 119900, 121300,
       124900, 128999, 129900, 131900, 134900, 139900, 139999, 140300,
       144900, 149900, 149999, 150800, 159900, 169900, 171999, 179900,
       179999, 189999], dtype=int64)]),
                                                  ['Brand', 'Model', 'Color',
                    

In [31]:
y_pred= pipe.predict(x_test)


In [32]:
y_pred

array([ 5.47226422e+04,  1.73386124e+04,  8.77159636e+03,  1.06178871e+04,
        4.14042620e+04,  7.57019238e+03,  2.51123343e+04,  1.17299963e+04,
        6.00217105e+03,  9.09879489e+03,  2.28050618e+04,  2.83397789e+04,
        1.80694048e+04,  1.09876838e+04,  2.31547906e+04,  3.78945823e+04,
        3.00826834e+04,  5.80538125e+03,  1.48009409e+04,  4.24942283e+04,
        1.10535811e+04,  2.07426177e+04,  2.81332816e+04,  7.87767387e+03,
        4.17013949e+03,  1.31351918e+04,  1.33795136e+04,  8.65628941e+03,
        2.22014469e+04,  6.65755822e+03,  1.59948828e+05,  7.10897558e+03,
        2.45880269e+04,  1.83973851e+04,  4.29699142e+04,  1.65960043e+04,
        2.19808878e+04,  3.79989943e+04,  7.21112453e+04,  1.13146160e+04,
        6.39999641e+03,  1.09231395e+04,  1.84990009e+04,  2.70399765e+04,
        2.65766037e+04,  9.29043815e+03,  3.14675187e+04,  1.04418957e+04,
        1.53481328e+04,  3.30558400e+04,  6.44684733e+04,  4.08211569e+04,
        2.32396487e+04,  

In [33]:
r2_score(y_test,y_pred)

0.9365184064122631

In [34]:
score=[]
for i in range(3000):
    x_train,x_test,y_train,y_test=train_test_split(x,y, test_size=0.2,random_state=i)
    lr=LinearRegression()
    pipe =make_pipeline(column_trans,lr)
    pipe.fit(x_train,y_train)
    y_pred= pipe.predict(x_test)
    score.append(r2_score(y_test,y_pred))

In [35]:
np.argmax(score)

236

In [36]:
score[np.argmax(score)]

0.970916560585745

In [37]:
x_train,x_test,y_train,y_test=train_test_split(x,y, test_size=0.2,random_state=np.argmax(score))
lr=LinearRegression()
pipe =make_pipeline(column_trans,lr)
pipe.fit(x_train,y_train)
y_pred= pipe.predict(x_test)
r2_score(y_test,y_pred)

0.970916560585745

In [38]:
import pickle

In [39]:
pickle.dump(pipe,open('LinearRegressionModel.pkl','wb'))

In [40]:
pipe.predict(pd.DataFrame([['OPPO','A53','Mint Cream','4 GB','64 GB',4.5,15990]],columns=['Brand','Model','Color','Memory','Storage','Rating','Original Price']))

array([12129.99502485])